# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: # Decimos en que evento se van a ejecutar las tareas
    # En este caso se ejecutara cuando se realice un push y un pull request
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: # nos dice si queremos ejecutar un workflow manualmente

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: # Son serie de pasos que queremos que ejecute el programa
  # This workflow contains a single job called "build"
  build:
    env: # Variables de entorno
      urs: anderson
      pw: hola90
      port: 8080
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # Corre una maquina de ubuntu

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: # dentro de la maquina de ubuntu corre estos pasos
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Mostrar mensaje"
        run: echo "Hola mundo"
      - name: "Mostrando variables de entorno"
        if: ${{env.urs == 'anderson1'}}
        run: |
          echo "Usuario: ${{env.urs}}"
          echo "Password: ${{env.pw}}" 
          echo "Puerto: ${{env.port}}"

